In [8]:
import os
import numpy as np
import pandas as pd

In [9]:
YEAR = 2010
QTR = 1

# List

In [10]:
DIR_DATA_CSV_LIST = "../data/csv/listing"

In [11]:
listing = pd.read_csv(
    f"{DIR_DATA_CSV_LIST}/{YEAR}QTR{QTR}_LIST.gz",
    sep="|",
    dtype={'Accession':str}
)
listing

,CIK,Company Name,Form Type,Date Filed,Filename
0,1000697,WATERS CORP /DE/,10-K,2010-02-26,https://sec.gov/Archives/edgar/data/1000697/00...
1,1001039,WALT DISNEY CO/,10-Q,2010-02-09,https://sec.gov/Archives/edgar/data/1001039/00...
2,1001082,DISH Network CORP,10-K,2010-03-01,https://sec.gov/Archives/edgar/data/1001082/00...
3,1001838,SOUTHERN COPPER CORP/,10-K,2010-02-26,https://sec.gov/Archives/edgar/data/1001838/00...
4,1002638,OPEN TEXT CORP,10-Q,2010-02-04,https://sec.gov/Archives/edgar/data/1002638/00...
5,1002910,AMEREN CORP,10-K,2010-02-26,https://sec.gov/Archives/edgar/data/1002910/00...
6,1004155,AGL RESOURCES INC,10-K,2010-02-04,https://sec.gov/Archives/edgar/data/1004155/00...
7,1004440,CONSTELLATION ENERGY GROUP INC,10-K,2010-02-26,https://sec.gov/Archives/edgar/data/1004440/00...

# XBRL

In [12]:
DIR_DATA_CSV_XBRL = "../data/csv/xbrl"

In [13]:
xbrl = pd.read_csv(
    f"{DIR_DATA_CSV_XBRL}/{YEAR}QTR{QTR}_XBRL.gz",
    sep="|",
    dtype={'Accession':str}
)
xbrl

,CIK,Company Name,Form Type,Date Filed,Year,Quarter,Filename,Filepath
0,1000697,WATERS CORP /DE/,10-K,2010-02-26,2010,1,https://sec.gov/Archives/edgar/data/1000697/00...,1000697/000095012310017583/wat-20091231.xml.gz
1,1001039,WALT DISNEY CO/,10-Q,2010-02-09,2010,1,https://sec.gov/Archives/edgar/data/1001039/00...,1001039/000119312510025949/dis-20100102.xml.gz
2,1001082,DISH Network CORP,10-K,2010-03-01,2010,1,https://sec.gov/Archives/edgar/data/1001082/00...,1001082/000095012310018671/dish-20091231.xml.gz
3,1001838,SOUTHERN COPPER CORP/,10-K,2010-02-26,2010,1,https://sec.gov/Archives/edgar/data/1001838/00...,1001838/000110465910010334/scco-20091231.xml.gz
4,1002638,OPEN TEXT CORP,10-Q,2010-02-04,2010,1,https://sec.gov/Archives/edgar/data/1002638/00...,1002638/000119312510021715/otex-20091231.xml.gz
5,1002910,AMEREN CORP,10-K,2010-02-26,2010,1,https://sec.gov/Archives/edgar/data/1002910/00...,1002910/000119312510043155/aee-20091231.xml.gz
6,1004155,AGL RESOURCES INC,10-K,2010-02-04,2010,1,https://sec.gov/Archives/edgar/data/1004155/00...,1004155/000100415510000016/agl-20091231.xml.gz
7,1004440,CONSTELLATION ENERGY GROUP INC,10-K,2010-02-26,2010,1,https://sec.gov/Archives/edgar/data/1004440/00...,1004440/000104746910001515/ceg-20091231.xml.gz

# GAAP

In [14]:
DIR_DATA_CSV_GAAP = "../data/csv/gaap"

In [15]:
gaap = pd.read_csv(
    f"{DIR_DATA_CSV_GAAP}/{YEAR}QTR{QTR}_GAAP.gz",
    sep="|",
    dtype={'Accession':str}
)
#df = df[df['CIK'] == 1000697]
#df.sort_values(['CIK', 'Year', 'Quarter'])
gaap

,CIK,Accession,Year,Quarter,FS,Rep,Type,Name,Value,Unit,Decimals,Context
0,1000697,000095012310017583,2010,1,pl,operating_cost,debit,us-gaap:costofgoodsandservicessold,5.948820e+08,USD,-3.0,TwelveMonthsEnded_31Dec2009
1,1000697,000095012310017583,2010,1,pl,gross_profit,calc,us-gaap:grossprofit,9.038180e+08,USD,-3.0,TwelveMonthsEnded_31Dec2009
2,1000697,000095012310017583,2010,1,pl,operating_expense_rd,debit,us-gaap:researchanddevelopmentexpense,7.715400e+07,USD,-3.0,TwelveMonthsEnded_31Dec2009
3,1000697,000095012310017583,2010,1,pl,operating_expense_sga,debit,us-gaap:sellinggeneralandadministrativeexpense,4.214030e+08,USD,-3.0,TwelveMonthsEnded_31Dec2009
4,1000697,000095012310017583,2010,1,pl,operating_income,calc,us-gaap:operatingincomeloss,3.946020e+08,USD,-3.0,TwelveMonthsEnded_31Dec2009
...,...,...,...,...,...,...,...,...,...,...,...,...
221,1004440,000104746910001515,2010,1,NaN,NaN,debit,us-gaap:longtermdebtnoncurrent,4.814000e+09,USD,-5.0,I2009
222,1004440,000104746910001515,2010,1,NaN,NaN,debit,us-gaap:otherliabilitiesnoncurrent,3.888000e+08,USD,-5.0,I2009
223,1004440,000104746910001515,2010,1,NaN,NaN,debit,us-gaap:minorityinterest,7.530000e+07,USD,-5.0,I2009
224,1004440,000104746910001515,2010,1,bs,stockholders_equity,calc,us-gaap:stockholdersequityincludingportionattr...,3.229600e+09,USD,-5.0,I2009_CommonStockMember
225,1004440,000104746910001515,2010,1,bs,total_equity_and_liabilities,calc,us-gaap:liabilitiesandstockholdersequity,2.354440e+10,USD,-5.0,I2009

In [16]:
a = [1,2,3]
a[::-1]

[3, 2, 1]